#!/bin/bash
#
osch=0
echo "1. Unix (Sun OS)"
echo "2. Linux (Red Hat)"

echo -n "selech your os choice [1 or 2]"
read osch

if [ $osch -eq 1 ] ; then 
	echo "you pick up unix (Sun OS)
else #### nested if i.e if whitin if ######
	if [ osch -eq 2 ] ; then
		echo "you pick up Linux (Red Hat)" 
	else
		echo "what you don`t like about Unix/Linux"
		fi
	fi
#
# 
