#!/bin/bash
#
#kasutaja tevitus skript2
#
read -p "siseta aeg: " aeg
if [[ $aeg -ge 6 ]] && [[ $aeg -le 11]]
then 
	echo "Hommikust!"
elif [[ $aeg -ge 12 ]] && [[ $aeg -le 17  ]]
then
	echo "tere päevast"
elif [[ $aeg -ge 18 ]] && [[ $aeg -le 21 ]]
then
	echo "Õhtust"
elif [[ $aeg -ge 22 ]] && [[ $aeg -le 24  ]]
then	
	echo "head ööd"
elif [[ $aeg-ge 1 ]] && [[ $ aeg -le 5 ]] 
then 
	echo "head ööd"
fi
#
#lõpp
