#!/bin/bash
#
#kasutaja tevitus skript2
#
read -p "siseta aeg: " aeg
read -p "sisesta nimi: " kasutaja
if [[ $aeg -ge 6 ]] && [[ $aeg -le 11]]
then 
	echo "Hommikust!"
	echo "Tere $kasutaja"
elif [[ $aeg -ge 12 ]] && [[ $aeg -le 17  ]]
then
	echo "tere päevast"
	echo "Tere $kasutaja"
elif [[ $aeg -ge 18 ]] && [[ $aeg -le 21 ]]
then
	echo "Õhtust"
	echo "Tere õhtust $kasutaja"
elif [[ $aeg -ge 22 ]] && [[ $aeg -le 24  ]]
then	
	echo "head ööd"
	echo "head ööd $kasutaja"
elif [[ $aeg-ge 1 ]] && [[ $ aeg -le 5 ]] 
then 
	echo "head ööd"
	echo "Head ööd $kasutaja"
fi
#
#lõpp
