#!/bin/bash
#
#
read -p "palun sisesta siia kuu number: " kuu
if test $kuu == 1
then 
	echo "on jaanuar"
elif test $kuu == 2
then
	echo "on veebruar"
elif test $kuu == 3
then
	echo "on märts"
elif test $kuu == 4
then
	echo "on aprill"
elif test $kuu == 5
then
	echo "on mai"
elif test $kuu == 6
then
	echo "on juuni"
elif test $kuu == 7
then
	echo "on juuli"
elif test  $kuu == 8
then
	echo "on august"
elif test $kuu == 9
then
	echo "on september"
elif test $kuu == 10
then
	echo "on oktoober"
elif test $kuu == 11
then 
	echo "on november"
elif test $kuu == 12
then
	echo "on detsember"
else
	echo "vigane sisend"
#
#lõpp
