#!/bin/bash 
#
#Tervitus
#
echo -n "sisesta on ees- ja perenimi:" #reavaheta ja annab küsimuse
read eesnimi perenimi #loebvastused ja jätab meelde
echo "Tere tulemast, $eesnimi $perenimi" #täidab 2 lünka
#
#lõpp
