#!/bin/bash
#
#küpsisetort
#
#
echo "sisestage kandiku pikkus ja laius:(cm) " 
read k_pikkus k_laius
echo "sisestage küpsise pikkus ja laius:(cm) "
read ky_pikkus ky_laius
echo "palun sisestage kihtide arv"
read kihiarv
echo "palun sisestage küpsiste arv pakis"
read pakis
kandik=`expr $k_pikkus \*$k_laius`
kypsis=`expr $ky_pikkus \*ky_laius`
pakke=`expr $kihiarv \* $kihis`
pakke2=`expr $pakke \/ 4pakis`
echo "tuleb osta $pakke2 pakki küpsist"
#
#lõpp
