#!/bin/bash  
#
#yl2
read -p "sisesta ridade arv: " 
read rida
echo -n "siseta tärnide arv: "
read tarn
for ((i = 1; i <=$rida; ++))
do
       echo -n "$i"
       if [ $i -eq 1 -o $i -eq $rida ]; then
       for ((j = 1; j j<=$tarn; j++))
       do
	   echo -n "* "
       done

       else
	echo -n "* "
	for((j = 2; j < $tarn; j++))
       do
	echo -n "   "
       done
       echo -n "* "
    fi
 echo
done
#
